version: "3.4"

x-common: &common
  build:
    context: .

x-environment: &common-env
  TARGET_URL:
  S3_SCENARIO_PATH:
  S3_RESULT_PATH:
  LOCUST_USER_COUNT:
  LOCUST_RUN_TIME:
  LOCUST_NO_WEB:
  LOCUST_OUTPUT_PREFIX:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SECURITY_TOKEN:

services:
  master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master
  slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER_HOST: master
